ALTER TABLE "api_key" ADD CONSTRAINT "api_key_name_length_chk" CHECK (length("api_key"."name") <= 120);--> statement-breakpoint
ALTER TABLE "api_key" ADD CONSTRAINT "api_key_lookup_secret_version_length_chk" CHECK (length("api_key"."lookup_secret_version") <= 32);--> statement-breakpoint
ALTER TABLE "api_key" ADD CONSTRAINT "api_key_key_prefix_length_chk" CHECK (length("api_key"."key_prefix") <= 32);--> statement-breakpoint
ALTER TABLE "audit_event" ADD CONSTRAINT "audit_event_action_length_chk" CHECK (length("audit_event"."action") <= 120);--> statement-breakpoint
ALTER TABLE "audit_event" ADD CONSTRAINT "audit_event_target_type_length_chk" CHECK (length("audit_event"."target_type") <= 120);--> statement-breakpoint
ALTER TABLE "execution_log" ADD CONSTRAINT "execution_log_error_code_length_chk" CHECK ("execution_log"."error_code" IS NULL OR length("execution_log"."error_code") <= 120);--> statement-breakpoint
ALTER TABLE "execution_log" ADD CONSTRAINT "execution_log_request_id_length_chk" CHECK ("execution_log"."request_id" IS NULL OR length("execution_log"."request_id") <= 200);--> statement-breakpoint
ALTER TABLE "execution_log" ADD CONSTRAINT "execution_log_error_message_length_chk" CHECK ("execution_log"."error_message" IS NULL OR length("execution_log"."error_message") <= 2000);--> statement-breakpoint
ALTER TABLE "invitation" ADD CONSTRAINT "invitation_email_length_chk" CHECK (length("invitation"."email") <= 320);--> statement-breakpoint
ALTER TABLE "invitation" ADD CONSTRAINT "invitation_token_digest_length_chk" CHECK (length("invitation"."token_digest") <= 128);--> statement-breakpoint
ALTER TABLE "logic" ADD CONSTRAINT "logic_name_length_chk" CHECK (length("logic"."name") <= 120);--> statement-breakpoint
ALTER TABLE "logic" ADD CONSTRAINT "logic_description_length_chk" CHECK ("logic"."description" IS NULL OR length("logic"."description") <= 500);--> statement-breakpoint
ALTER TABLE "logic_version" ADD CONSTRAINT "logic_version_release_notes_length_chk" CHECK ("logic_version"."release_notes" IS NULL OR length("logic_version"."release_notes") <= 2000);--> statement-breakpoint
ALTER TABLE "org" ADD CONSTRAINT "org_name_length_chk" CHECK (length("org"."name") <= 120);--> statement-breakpoint
ALTER TABLE "org" ADD CONSTRAINT "org_plan_length_chk" CHECK (length("org"."plan") <= 32);--> statement-breakpoint
ALTER TABLE "org_deletion_job" ADD CONSTRAINT "org_deletion_job_slug_snapshot_length_chk" CHECK (length("org_deletion_job"."org_slug_snapshot") <= 63);--> statement-breakpoint
ALTER TABLE "org_deletion_job" ADD CONSTRAINT "org_deletion_job_name_snapshot_length_chk" CHECK (length("org_deletion_job"."org_name_snapshot") <= 120);--> statement-breakpoint
ALTER TABLE "org_deletion_job" ADD CONSTRAINT "org_deletion_job_last_error_length_chk" CHECK ("org_deletion_job"."last_error" IS NULL OR length("org_deletion_job"."last_error") <= 2000);--> statement-breakpoint
ALTER TABLE "user" ADD CONSTRAINT "user_email_length_chk" CHECK (length("user"."email") <= 320);--> statement-breakpoint
ALTER TABLE "user" ADD CONSTRAINT "user_name_length_chk" CHECK (length("user"."name") <= 120);--> statement-breakpoint
ALTER TABLE "user" ADD CONSTRAINT "user_image_length_chk" CHECK ("user"."image" IS NULL OR length("user"."image") <= 2048);--> statement-breakpoint
ALTER TABLE "workspace" ADD CONSTRAINT "workspace_name_length_chk" CHECK (length("workspace"."name") <= 120);--> statement-breakpoint
ALTER TABLE "workspace" ADD CONSTRAINT "workspace_description_length_chk" CHECK ("workspace"."description" IS NULL OR length("workspace"."description") <= 500);