// P3.2.b — production Drizzle schema, translating [design_p3_schema.md v7] into
// drizzle-orm pgTable definitions. Twelve production tables (user / org /
// workspace / membership / invitation / logic / logic_version / api_key /
// api_key_logic_scope / execution_log / audit_event / org_deletion_job) plus
// Better Auth's session / account / verification.
//
// Drizzle covers most of the DDL natively. The following SQL DDL elements are
// emitted by hand in the generated initial migration because the Drizzle API
// has no clean expression for them:
//
//   1. `DEFERRABLE INITIALLY IMMEDIATE` on foreign keys. Drizzle's
//      `.onDelete("no action")` produces NO ACTION but cannot add the
//      DEFERRABLE modifier. The user / api_key / logic_version cross-table FKs
//      all need it (see [design_p3_schema.md §4 リレーション一覧]).
//   2. `CREATE EXTENSION` statements for `citext` / `pgcrypto`.
//   3. `BEFORE UPDATE` triggers that call `set_updated_at()`. Drizzle's
//      `.$onUpdate()` fires only when Drizzle is the writer; we need DB-level
//      triggers so raw SQL writes (psql, migrations) also stamp updated_at.
//   4. Some CHECK expressions that reference `jsonb_typeof(...)` or compound
//      multi-column conditions can be expressed via Drizzle's `check()`, but
//      we keep them here for documentation parity with design_p3_schema.md.
//
// Better Auth is reconciled with the production user shape in apps/api/src/auth.ts:
// user.id is generated by the DB uuidv7() default, emailVerified maps to
// email_verified_at, and last_login_at / deleted_at are maintained by auth hooks.

import { sql } from 'drizzle-orm';
import {
  boolean,
  check,
  customType,
  foreignKey,
  index,
  integer,
  jsonb,
  pgTable,
  primaryKey,
  text,
  timestamp,
  unique,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core';

// citext is inlined here (rather than imported from ./types.ts) because
// drizzle-kit's schema loader does its own module resolution that does not
// honor our tsconfig's `moduleResolution: bundler`, so `./types.js` fails to
// resolve to types.ts at generation time. The helper is one-line so the
// inline cost is trivial.
const citext = customType<{ data: string; driverData: string }>({
  dataType() {
    return 'citext';
  },
});

const uuidv7 = sql`uuidv7()`;

// ─────────────────────────────────────────────────────────────────────────
// 3.1 user — global identity. Physical delete is blocked; we redact + set
//   deleted_at. All cross-table FKs to user are NO ACTION DEFERRABLE so
//   `DELETE FROM "user"` raises rather than orphaning rows.
// ─────────────────────────────────────────────────────────────────────────
export const user = pgTable(
  'user',
  {
    id: uuid('id').primaryKey().default(uuidv7),
    email: citext('email').notNull(),
    name: text('name').notNull(),
    image: text('image'),
    emailVerifiedAt: timestamp('email_verified_at', { withTimezone: true }),
    lastLoginAt: timestamp('last_login_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    deletedAt: timestamp('deleted_at', { withTimezone: true }),
  },
  (t) => [
    check('user_email_length_chk', sql`length(${t.email}) <= 320`),
    check('user_name_length_chk', sql`length(${t.name}) <= 120`),
    check(
      'user_image_length_chk',
      sql`${t.image} IS NULL OR length(${t.image}) <= 2048`,
    ),
    uniqueIndex('user_email_uniq').on(t.email),
  ],
);

// ─────────────────────────────────────────────────────────────────────────
// 3.2 org — tenant root. lifecycle_status / deleted_at / purge_requested_at
//   are tied by `org_lifecycle_consistency_chk` (v7). Slug uniqueness holds
//   until physical PURGE so the 30-day recovery window keeps URLs working.
// ─────────────────────────────────────────────────────────────────────────
export const org = pgTable(
  'org',
  {
    id: uuid('id').primaryKey().default(uuidv7),
    slug: text('slug').notNull(),
    name: text('name').notNull(),
    plan: text('plan').notNull().default('free'),
    lifecycleStatus: text('lifecycle_status').notNull().default('active'),
    purgeRequestedAt: timestamp('purge_requested_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    deletedAt: timestamp('deleted_at', { withTimezone: true }),
    createdActorType: text('created_actor_type').notNull(),
    createdActorId: uuid('created_actor_id'),
    updatedActorType: text('updated_actor_type'),
    updatedActorId: uuid('updated_actor_id'),
  },
  (t) => [
    check(
      'org_slug_format_chk',
      sql`${t.slug} ~ '^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$'`,
    ),
    check('org_name_length_chk', sql`length(${t.name}) <= 120`),
    check('org_plan_length_chk', sql`length(${t.plan}) <= 32`),
    check(
      'org_lifecycle_status_chk',
      sql`${t.lifecycleStatus} IN ('active', 'deleting', 'purging')`,
    ),
    check(
      'org_lifecycle_consistency_chk',
      sql`(
        ${t.lifecycleStatus} = 'active'
        AND ${t.deletedAt} IS NULL
        AND ${t.purgeRequestedAt} IS NULL
      ) OR (
        ${t.lifecycleStatus} IN ('deleting', 'purging')
        AND ${t.deletedAt} IS NOT NULL
        AND ${t.purgeRequestedAt} IS NOT NULL
      )`,
    ),
    check(
      'org_created_actor_type_chk',
      sql`${t.createdActorType} IN ('user', 'system')`,
    ),
    check(
      'org_updated_actor_type_chk',
      sql`${t.updatedActorType} IS NULL OR ${t.updatedActorType} IN ('user', 'system')`,
    ),
    check(
      'org_created_actor_consistency_chk',
      sql`(${t.createdActorType} = 'user' AND ${t.createdActorId} IS NOT NULL)
          OR (${t.createdActorType} = 'system' AND ${t.createdActorId} IS NULL)`,
    ),
    check(
      'org_updated_actor_consistency_chk',
      sql`(${t.updatedActorType} IS NULL AND ${t.updatedActorId} IS NULL)
          OR (${t.updatedActorType} = 'user' AND ${t.updatedActorId} IS NOT NULL)
          OR (${t.updatedActorType} = 'system' AND ${t.updatedActorId} IS NULL)`,
    ),
    uniqueIndex('org_slug_not_purged_uniq')
      .on(t.slug)
      .where(sql`lifecycle_status IN ('active', 'deleting', 'purging')`),
    index('org_lifecycle_purge_queue_idx')
      .on(t.purgeRequestedAt)
      .where(sql`lifecycle_status IN ('deleting', 'purging')`),
  ],
);

// ─────────────────────────────────────────────────────────────────────────
// 3.3 workspace — project-scope under org. The (org_id, id) UNIQUE is the
//   composite-FK anchor that audit_event uses to enforce org/workspace
//   consistency.
// ─────────────────────────────────────────────────────────────────────────
export const workspace = pgTable(
  'workspace',
  {
    id: uuid('id').primaryKey().default(uuidv7),
    orgId: uuid('org_id')
      .notNull()
      .references(() => org.id, { onDelete: 'cascade' }),
    slug: text('slug').notNull(),
    name: text('name').notNull(),
    description: text('description'),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    deletedAt: timestamp('deleted_at', { withTimezone: true }),
    createdActorType: text('created_actor_type').notNull(),
    createdActorId: uuid('created_actor_id'),
    updatedActorType: text('updated_actor_type'),
    updatedActorId: uuid('updated_actor_id'),
  },
  (t) => [
    check(
      'workspace_slug_format_chk',
      sql`${t.slug} ~ '^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$'`,
    ),
    check('workspace_name_length_chk', sql`length(${t.name}) <= 120`),
    check(
      'workspace_description_length_chk',
      sql`${t.description} IS NULL OR length(${t.description}) <= 500`,
    ),
    check(
      'workspace_created_actor_type_chk',
      sql`${t.createdActorType} IN ('user', 'system')`,
    ),
    check(
      'workspace_updated_actor_type_chk',
      sql`${t.updatedActorType} IS NULL OR ${t.updatedActorType} IN ('user', 'system')`,
    ),
    check(
      'workspace_created_actor_consistency_chk',
      sql`(${t.createdActorType} = 'user' AND ${t.createdActorId} IS NOT NULL)
          OR (${t.createdActorType} = 'system' AND ${t.createdActorId} IS NULL)`,
    ),
    check(
      'workspace_updated_actor_consistency_chk',
      sql`(${t.updatedActorType} IS NULL AND ${t.updatedActorId} IS NULL)
          OR (${t.updatedActorType} = 'user' AND ${t.updatedActorId} IS NOT NULL)
          OR (${t.updatedActorType} = 'system' AND ${t.updatedActorId} IS NULL)`,
    ),
    // Composite UNIQUE constraint (not a partial unique index) because it
    // serves as the FK target for audit_event(org_id, workspace_id). UNIQUE
    // CONSTRAINTs are emitted inside CREATE TABLE so they're available before
    // any subsequent ALTER TABLE ADD FOREIGN KEY runs in the same migration.
    unique('workspace_org_id_id_uniq').on(t.orgId, t.id),
    uniqueIndex('workspace_org_slug_active_uniq')
      .on(t.orgId, t.slug)
      .where(sql`deleted_at IS NULL`),
    index('workspace_org_id_active_idx')
      .on(t.orgId, t.createdAt.desc())
      .where(sql`deleted_at IS NULL`),
  ],
);

// ─────────────────────────────────────────────────────────────────────────
// 3.4 membership — user × org with role. user_id FK is NO ACTION DEFERRABLE
//   (v7) to block user physical deletion at the DB level. Lifecycle is
//   accept-only: active rows have removed_at = NULL.
// ─────────────────────────────────────────────────────────────────────────
export const membership = pgTable(
  'membership',
  {
    id: uuid('id').primaryKey().default(uuidv7),
    orgId: uuid('org_id')
      .notNull()
      .references(() => org.id, { onDelete: 'cascade' }),
    // v7: NO ACTION (DEFERRABLE INITIALLY IMMEDIATE is added in the initial migration)
    userId: uuid('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'no action' }),
    role: text('role').notNull(),
    invitedActorType: text('invited_actor_type').notNull(),
    invitedActorId: uuid('invited_actor_id'),
    invitedAt: timestamp('invited_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    joinedAt: timestamp('joined_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    removedAt: timestamp('removed_at', { withTimezone: true }),
  },
  (t) => [
    check(
      'membership_role_chk',
      sql`${t.role} IN ('owner', 'admin', 'editor', 'viewer', 'runner')`,
    ),
    check(
      'membership_invited_actor_type_chk',
      sql`${t.invitedActorType} IN ('user', 'system')`,
    ),
    check(
      'membership_invited_actor_consistency_chk',
      sql`(${t.invitedActorType} = 'user' AND ${t.invitedActorId} IS NOT NULL)
          OR (${t.invitedActorType} = 'system' AND ${t.invitedActorId} IS NULL)`,
    ),
    uniqueIndex('membership_org_user_not_removed_uniq')
      .on(t.orgId, t.userId)
      .where(sql`removed_at IS NULL`),
    index('membership_user_not_removed_idx')
      .on(t.userId)
      .where(sql`removed_at IS NULL`),
  ],
);

// ─────────────────────────────────────────────────────────────────────────
// 3.5 invitation — pending → accepted XOR revoked. v6 adds CHECK to block
//   late accepts (accepted_at <= expires_at).
// ─────────────────────────────────────────────────────────────────────────
export const invitation = pgTable(
  'invitation',
  {
    id: uuid('id').primaryKey().default(uuidv7),
    orgId: uuid('org_id')
      .notNull()
      .references(() => org.id, { onDelete: 'cascade' }),
    email: citext('email').notNull(),
    role: text('role').notNull(),
    tokenDigest: text('token_digest').notNull(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    acceptedAt: timestamp('accepted_at', { withTimezone: true }),
    revokedAt: timestamp('revoked_at', { withTimezone: true }),
    invitedActorType: text('invited_actor_type').notNull(),
    invitedActorId: uuid('invited_actor_id'),
    acceptedActorType: text('accepted_actor_type'),
    acceptedActorId: uuid('accepted_actor_id'),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    check('invitation_email_length_chk', sql`length(${t.email}) <= 320`),
    check(
      'invitation_token_digest_length_chk',
      sql`length(${t.tokenDigest}) <= 128`,
    ),
    check(
      'invitation_role_chk',
      sql`${t.role} IN ('owner', 'admin', 'editor', 'viewer', 'runner')`,
    ),
    check(
      'invitation_invited_actor_type_chk',
      sql`${t.invitedActorType} IN ('user', 'system')`,
    ),
    check(
      'invitation_accepted_actor_type_chk',
      sql`${t.acceptedActorType} IS NULL OR ${t.acceptedActorType} IN ('user', 'system')`,
    ),
    check(
      'invitation_terminal_state_chk',
      sql`${t.acceptedAt} IS NULL OR ${t.revokedAt} IS NULL`,
    ),
    check(
      'invitation_accept_before_expiry_chk',
      sql`${t.acceptedAt} IS NULL OR ${t.acceptedAt} <= ${t.expiresAt}`,
    ),
    check(
      'invitation_accepted_pair_chk',
      sql`(${t.acceptedAt} IS NULL
            AND ${t.acceptedActorType} IS NULL
            AND ${t.acceptedActorId} IS NULL)
          OR (${t.acceptedAt} IS NOT NULL
            AND ${t.acceptedActorType} IS NOT NULL
            AND (
              (${t.acceptedActorType} = 'user' AND ${t.acceptedActorId} IS NOT NULL)
              OR (${t.acceptedActorType} = 'system' AND ${t.acceptedActorId} IS NULL)
            ))`,
    ),
    check(
      'invitation_invited_actor_consistency_chk',
      sql`(${t.invitedActorType} = 'user' AND ${t.invitedActorId} IS NOT NULL)
          OR (${t.invitedActorType} = 'system' AND ${t.invitedActorId} IS NULL)`,
    ),
    uniqueIndex('invitation_token_digest_uniq').on(t.tokenDigest),
    uniqueIndex('invitation_org_email_open_uniq')
      .on(t.orgId, t.email)
      .where(sql`accepted_at IS NULL AND revoked_at IS NULL`),
    index('invitation_email_open_idx')
      .on(t.email)
      .where(sql`accepted_at IS NULL AND revoked_at IS NULL`),
  ],
);

// ─────────────────────────────────────────────────────────────────────────
// 3.6 logic — draft + production pin. production_version_id is a composite FK
//   to logic_version, added in the initial migration after both tables
//   exist (circular dependency).
// ─────────────────────────────────────────────────────────────────────────
export const logic = pgTable(
  'logic',
  {
    id: uuid('id').primaryKey().default(uuidv7),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspace.id, { onDelete: 'cascade' }),
    slug: text('slug').notNull(),
    name: text('name').notNull(),
    description: text('description'),
    draftData: jsonb('draft_data').notNull(),
    draftWorkspaceConfig: jsonb('draft_workspace_config'),
    draftSchemaVersion: text('draft_schema_version').notNull().default('2'),
    draftRevision: integer('draft_revision').notNull().default(0),
    productionVersionId: uuid('production_version_id'),
    draftUpdatedAt: timestamp('draft_updated_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    draftUpdatedActorType: text('draft_updated_actor_type').notNull(),
    draftUpdatedActorId: uuid('draft_updated_actor_id'),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    deletedAt: timestamp('deleted_at', { withTimezone: true }),
    createdActorType: text('created_actor_type').notNull(),
    createdActorId: uuid('created_actor_id'),
    updatedActorType: text('updated_actor_type'),
    updatedActorId: uuid('updated_actor_id'),
  },
  (t) => [
    check(
      'logic_slug_format_chk',
      sql`${t.slug} ~ '^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$'`,
    ),
    check('logic_name_length_chk', sql`length(${t.name}) <= 120`),
    check(
      'logic_description_length_chk',
      sql`${t.description} IS NULL OR length(${t.description}) <= 500`,
    ),
    check(
      'logic_draft_schema_version_matches_chk',
      sql`jsonb_typeof(${t.draftData}->'version') = 'string'
          AND ${t.draftSchemaVersion} = ${t.draftData}->>'version'`,
    ),
    check(
      'logic_draft_workspace_config_object_chk',
      sql`${t.draftWorkspaceConfig} IS NULL OR jsonb_typeof(${t.draftWorkspaceConfig}) = 'object'`,
    ),
    check(
      'logic_created_actor_type_chk',
      sql`${t.createdActorType} IN ('user', 'system')`,
    ),
    check(
      'logic_updated_actor_type_chk',
      sql`${t.updatedActorType} IS NULL OR ${t.updatedActorType} IN ('user', 'api_key', 'system')`,
    ),
    check(
      'logic_draft_updated_actor_type_chk',
      sql`${t.draftUpdatedActorType} IN ('user', 'system')`,
    ),
    check(
      'logic_created_actor_consistency_chk',
      sql`(${t.createdActorType} = 'user' AND ${t.createdActorId} IS NOT NULL)
          OR (${t.createdActorType} = 'system' AND ${t.createdActorId} IS NULL)`,
    ),
    check(
      'logic_updated_actor_consistency_chk',
      sql`(${t.updatedActorType} IS NULL AND ${t.updatedActorId} IS NULL)
          OR (${t.updatedActorType} IN ('user', 'api_key') AND ${t.updatedActorId} IS NOT NULL)
          OR (${t.updatedActorType} = 'system' AND ${t.updatedActorId} IS NULL)`,
    ),
    check(
      'logic_draft_updated_actor_consistency_chk',
      sql`(${t.draftUpdatedActorType} = 'user' AND ${t.draftUpdatedActorId} IS NOT NULL)
          OR (${t.draftUpdatedActorType} = 'system' AND ${t.draftUpdatedActorId} IS NULL)`,
    ),
    // FK target for execution_log / api_key_logic_scope — see workspace
    // comment above for why this is a UNIQUE CONSTRAINT, not an index.
    unique('logic_workspace_id_id_uniq').on(t.workspaceId, t.id),
    uniqueIndex('logic_workspace_slug_active_uniq')
      .on(t.workspaceId, t.slug)
      .where(sql`deleted_at IS NULL`),
    index('logic_workspace_active_idx')
      .on(t.workspaceId, t.draftUpdatedAt.desc())
      .where(sql`deleted_at IS NULL`),
  ],
);

// ─────────────────────────────────────────────────────────────────────────
// 3.7 logic_version — immutable snapshots. The 3-tuple (logic_id, id,
//   version_number) UNIQUE is the anchor for execution_log's composite FK.
// ─────────────────────────────────────────────────────────────────────────
export const logicVersion = pgTable(
  'logic_version',
  {
    id: uuid('id').primaryKey().default(uuidv7),
    workspaceId: uuid('workspace_id').notNull(),
    logicId: uuid('logic_id').notNull(),
    versionNumber: integer('version_number').notNull(),
    schemaVersion: text('schema_version').notNull().default('2'),
    data: jsonb('data').notNull(),
    workspaceConfig: jsonb('workspace_config'),
    releaseNotes: text('release_notes'),
    publishedAt: timestamp('published_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    publishedActorType: text('published_actor_type').notNull(),
    publishedActorId: uuid('published_actor_id'),
  },
  (t) => [
    check(
      'logic_version_version_number_positive_chk',
      sql`${t.versionNumber} > 0`,
    ),
    check(
      'logic_version_schema_version_matches_chk',
      sql`jsonb_typeof(${t.data}->'version') = 'string'
          AND ${t.schemaVersion} = ${t.data}->>'version'`,
    ),
    check(
      'logic_version_workspace_config_object_chk',
      sql`${t.workspaceConfig} IS NULL OR jsonb_typeof(${t.workspaceConfig}) = 'object'`,
    ),
    check(
      'logic_version_release_notes_length_chk',
      sql`${t.releaseNotes} IS NULL OR length(${t.releaseNotes}) <= 2000`,
    ),
    check(
      'logic_version_published_actor_type_chk',
      sql`${t.publishedActorType} IN ('user', 'system')`,
    ),
    check(
      'logic_version_published_actor_consistency_chk',
      sql`(${t.publishedActorType} = 'user' AND ${t.publishedActorId} IS NOT NULL)
          OR (${t.publishedActorType} = 'system' AND ${t.publishedActorId} IS NULL)`,
    ),
    unique('logic_version_logic_number_uniq').on(t.logicId, t.versionNumber),
    unique('logic_version_workspace_id_id_uniq').on(t.workspaceId, t.id),
    // FK target for logic.production_version_id composite FK (added in
    // the initial migration).
    unique('logic_version_logic_id_id_uniq').on(t.logicId, t.id),
    // FK target for execution_log's 3-tuple composite FK.
    unique('logic_version_logic_id_id_number_uniq').on(
      t.logicId,
      t.id,
      t.versionNumber,
    ),
    // FK target for logic_version_data_snapshot's tenant-consistency composite
    // FK (workspace_id, logic_id, logic_version_id) — see §3.7.
    unique('logic_version_workspace_logic_id_uniq').on(
      t.workspaceId,
      t.logicId,
      t.id,
    ),
    index('logic_version_logic_id_desc_idx').on(
      t.logicId,
      t.versionNumber.desc(),
    ),
    foreignKey({
      columns: [t.workspaceId, t.logicId],
      foreignColumns: [logic.workspaceId, logic.id],
      name: 'logic_version_workspace_logic_fk',
    }).onDelete('cascade'),
  ],
);

// ─────────────────────────────────────────────────────────────────────────
// 3.8 api_key — HMAC lookup + argon2 verify. v6 adds lookup_secret_version
//   for HMAC server-secret rotation.
// ─────────────────────────────────────────────────────────────────────────
export const apiKey = pgTable(
  'api_key',
  {
    id: uuid('id').primaryKey().default(uuidv7),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspace.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    lookupSecretVersion: text('lookup_secret_version').notNull().default('v1'),
    lookupDigest: text('lookup_digest').notNull(),
    keyHash: text('key_hash').notNull(),
    keyPrefix: text('key_prefix').notNull(),
    role: text('role').notNull(),
    scopeMode: text('scope_mode').notNull().default('all'),
    expiresAt: timestamp('expires_at', { withTimezone: true }),
    lastUsedAt: timestamp('last_used_at', { withTimezone: true }),
    revokedAt: timestamp('revoked_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    createdActorType: text('created_actor_type').notNull(),
    createdActorId: uuid('created_actor_id'),
  },
  (t) => [
    check('api_key_name_length_chk', sql`length(${t.name}) <= 120`),
    check(
      'api_key_lookup_secret_version_length_chk',
      sql`length(${t.lookupSecretVersion}) <= 32`,
    ),
    check('api_key_key_prefix_length_chk', sql`length(${t.keyPrefix}) <= 32`),
    check('api_key_role_chk', sql`${t.role} IN ('editor', 'viewer', 'runner')`),
    check(
      'api_key_scope_mode_chk',
      sql`${t.scopeMode} IN ('all', 'allowlist')`,
    ),
    check(
      'api_key_created_actor_type_chk',
      sql`${t.createdActorType} IN ('user', 'system')`,
    ),
    check(
      'api_key_created_actor_consistency_chk',
      sql`(${t.createdActorType} = 'user' AND ${t.createdActorId} IS NOT NULL)
          OR (${t.createdActorType} = 'system' AND ${t.createdActorId} IS NULL)`,
    ),
    // FK target for api_key_logic_scope / execution_log / audit_event
    // composite FKs — same reason as workspace.orgIdIdUniq above.
    unique('api_key_workspace_id_id_uniq').on(t.workspaceId, t.id),
    uniqueIndex('api_key_lookup_digest_uniq').on(
      t.lookupSecretVersion,
      t.lookupDigest,
    ),
    index('api_key_workspace_not_revoked_idx')
      .on(t.workspaceId, t.createdAt.desc())
      .where(sql`revoked_at IS NULL`),
  ],
);

// ─────────────────────────────────────────────────────────────────────────
// 3.9 api_key_logic_scope — allowlist join. Composite PK is tenant-prefixed.
// ─────────────────────────────────────────────────────────────────────────
export const apiKeyLogicScope = pgTable(
  'api_key_logic_scope',
  {
    workspaceId: uuid('workspace_id').notNull(),
    apiKeyId: uuid('api_key_id').notNull(),
    logicId: uuid('logic_id').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    primaryKey({ columns: [t.workspaceId, t.apiKeyId, t.logicId] }),
    foreignKey({
      columns: [t.workspaceId, t.apiKeyId],
      foreignColumns: [apiKey.workspaceId, apiKey.id],
      name: 'api_key_logic_scope_api_key_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [t.workspaceId, t.logicId],
      foreignColumns: [logic.workspaceId, logic.id],
      name: 'api_key_logic_scope_logic_fk',
    }).onDelete('cascade'),
    index('api_key_logic_scope_workspace_logic_idx').on(
      t.workspaceId,
      t.logicId,
    ),
  ],
);

// ─────────────────────────────────────────────────────────────────────────
// 3.10 execution_log — every evaluate() call. v6 splits caller into
//   (actor_type × channel). The 3-tuple FK to logic_version is NO ACTION
//   DEFERRABLE (added in the initial migration).
// ─────────────────────────────────────────────────────────────────────────
export const executionLog = pgTable(
  'execution_log',
  {
    id: uuid('id').primaryKey().default(uuidv7),
    workspaceId: uuid('workspace_id').notNull(),
    logicId: uuid('logic_id').notNull(),
    logicVersionId: uuid('logic_version_id'),
    requestedVersionType: text('requested_version_type').notNull(),
    requestedVersionNumber: integer('requested_version_number'),
    resolvedVersionNumber: integer('resolved_version_number'),
    inputs: jsonb('inputs'),
    result: jsonb('result'),
    trace: jsonb('trace'),
    status: text('status').notNull(),
    callerActorType: text('caller_actor_type').notNull(),
    callerChannel: text('caller_channel').notNull(),
    // user FK is NO ACTION (DEFERRABLE added in the initial migration)
    callerUserId: uuid('caller_user_id').references(() => user.id, {
      onDelete: 'no action',
    }),
    callerApiKeyId: uuid('caller_api_key_id'),
    errorCode: text('error_code'),
    requestId: text('request_id'),
    latencyMs: integer('latency_ms').notNull(),
    errorMessage: text('error_message'),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    check(
      'execution_log_requested_version_type_chk',
      sql`${t.requestedVersionType} IN ('draft', 'latest', 'production', 'version')`,
    ),
    check(
      'execution_log_requested_version_number_positive_chk',
      sql`${t.requestedVersionNumber} IS NULL OR ${t.requestedVersionNumber} > 0`,
    ),
    check(
      'execution_log_resolved_version_number_positive_chk',
      sql`${t.resolvedVersionNumber} IS NULL OR ${t.resolvedVersionNumber} > 0`,
    ),
    check(
      'execution_log_status_chk',
      sql`${t.status} IN ('ok', 'no_match', 'error')`,
    ),
    check(
      'execution_log_caller_actor_type_chk',
      sql`${t.callerActorType} IN ('user', 'api_key', 'system')`,
    ),
    check(
      'execution_log_caller_channel_chk',
      sql`${t.callerChannel} IN ('web', 'api_key', 'mcp', 'system')`,
    ),
    check(
      'execution_log_latency_ms_non_negative_chk',
      sql`${t.latencyMs} >= 0`,
    ),
    check(
      'execution_log_error_code_length_chk',
      sql`${t.errorCode} IS NULL OR length(${t.errorCode}) <= 120`,
    ),
    check(
      'execution_log_request_id_length_chk',
      sql`${t.requestId} IS NULL OR length(${t.requestId}) <= 200`,
    ),
    check(
      'execution_log_error_message_length_chk',
      sql`${t.errorMessage} IS NULL OR length(${t.errorMessage}) <= 2000`,
    ),
    check(
      'execution_log_status_payload_chk',
      sql`(${t.status} IN ('ok', 'no_match')
            AND ${t.inputs} IS NOT NULL
            AND ${t.result} IS NOT NULL
            AND ${t.trace} IS NOT NULL
            AND ${t.errorMessage} IS NULL
            AND ${t.errorCode} IS NULL)
          OR (${t.status} = 'error'
            AND ${t.result} IS NULL
            AND ${t.trace} IS NULL
            AND ${t.errorMessage} IS NOT NULL)`,
    ),
    check(
      'execution_log_requested_version_chk',
      sql`(${t.requestedVersionType} = 'draft'
            AND ${t.logicVersionId} IS NULL
            AND ${t.requestedVersionNumber} IS NULL
            AND ${t.resolvedVersionNumber} IS NULL)
          OR (${t.requestedVersionType} IN ('latest', 'production')
            AND ${t.logicVersionId} IS NOT NULL
            AND ${t.requestedVersionNumber} IS NULL
            AND ${t.resolvedVersionNumber} IS NOT NULL)
          OR (${t.requestedVersionType} = 'version'
            AND ${t.logicVersionId} IS NOT NULL
            AND ${t.requestedVersionNumber} IS NOT NULL
            AND ${t.resolvedVersionNumber} IS NOT NULL
            AND ${t.requestedVersionNumber} = ${t.resolvedVersionNumber})`,
    ),
    check(
      'execution_log_caller_chk',
      sql`(${t.callerActorType} = 'user'
            AND ${t.callerChannel} = 'web'
            AND ${t.callerUserId} IS NOT NULL
            AND ${t.callerApiKeyId} IS NULL)
          OR (${t.callerActorType} = 'api_key'
            AND ${t.callerChannel} IN ('api_key', 'mcp')
            AND ${t.callerUserId} IS NULL
            AND ${t.callerApiKeyId} IS NOT NULL)
          OR (${t.callerActorType} = 'system'
            AND ${t.callerChannel} = 'system'
            AND ${t.callerUserId} IS NULL
            AND ${t.callerApiKeyId} IS NULL)`,
    ),
    foreignKey({
      columns: [t.workspaceId, t.logicId],
      foreignColumns: [logic.workspaceId, logic.id],
      name: 'execution_log_workspace_logic_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [t.logicId, t.logicVersionId, t.resolvedVersionNumber],
      foreignColumns: [
        logicVersion.logicId,
        logicVersion.id,
        logicVersion.versionNumber,
      ],
      name: 'execution_log_version_tuple_fk',
    }).onDelete('no action'),
    foreignKey({
      columns: [t.workspaceId, t.callerApiKeyId],
      foreignColumns: [apiKey.workspaceId, apiKey.id],
      name: 'execution_log_caller_api_key_fk',
    }).onDelete('no action'),
    index('execution_log_logic_created_idx').on(t.logicId, t.createdAt.desc()),
    index('execution_log_workspace_created_idx').on(
      t.workspaceId,
      t.createdAt.desc(),
    ),
    index('execution_log_created_at_idx').on(t.createdAt),
    index('execution_log_workspace_requested_type_created_idx').on(
      t.workspaceId,
      t.requestedVersionType,
      t.createdAt.desc(),
    ),
    index('execution_log_request_id_idx')
      .on(t.requestId)
      .where(sql`request_id IS NOT NULL`),
    index('execution_log_error_code_created_idx')
      .on(t.errorCode, t.createdAt.desc())
      .where(sql`error_code IS NOT NULL`),
    index('execution_log_workspace_channel_created_idx').on(
      t.workspaceId,
      t.callerChannel,
      t.createdAt.desc(),
    ),
  ],
);

// ─────────────────────────────────────────────────────────────────────────
// 3.11 audit_event — security/product/system events. Separate retention per
//   event_class (security ≥ 1 year). actor_user_id FK is NO ACTION
//   DEFERRABLE (added in the initial migration).
// ─────────────────────────────────────────────────────────────────────────
export const auditEvent = pgTable(
  'audit_event',
  {
    id: uuid('id').primaryKey().default(uuidv7),
    orgId: uuid('org_id')
      .notNull()
      .references(() => org.id, { onDelete: 'cascade' }),
    workspaceId: uuid('workspace_id'),
    eventClass: text('event_class').notNull(),
    actorType: text('actor_type').notNull(),
    actorUserId: uuid('actor_user_id').references(() => user.id, {
      onDelete: 'no action',
    }),
    actorApiKeyId: uuid('actor_api_key_id'),
    actorPersona: text('actor_persona').notNull().default('unknown'),
    actorChannel: text('actor_channel').notNull(),
    action: text('action').notNull(),
    targetType: text('target_type').notNull(),
    targetId: uuid('target_id'),
    metadata: jsonb('metadata').notNull().default(sql`'{}'::jsonb`),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    check(
      'audit_event_event_class_chk',
      sql`${t.eventClass} IN ('security', 'product', 'system')`,
    ),
    check(
      'audit_event_actor_type_chk',
      sql`${t.actorType} IN ('user', 'api_key', 'system')`,
    ),
    check(
      'audit_event_actor_persona_chk',
      sql`${t.actorPersona} IN ('installer', 'author', 'unknown')`,
    ),
    check(
      'audit_event_actor_channel_chk',
      sql`${t.actorChannel} IN ('web', 'api_key', 'mcp', 'system')`,
    ),
    check('audit_event_action_length_chk', sql`length(${t.action}) <= 120`),
    check(
      'audit_event_target_type_length_chk',
      sql`length(${t.targetType}) <= 120`,
    ),
    check(
      'audit_event_actor_consistency_chk',
      sql`(${t.actorType} = 'user' AND ${t.actorUserId} IS NOT NULL AND ${t.actorApiKeyId} IS NULL)
          OR (${t.actorType} = 'api_key' AND ${t.actorUserId} IS NULL AND ${t.actorApiKeyId} IS NOT NULL)
          OR (${t.actorType} = 'system' AND ${t.actorUserId} IS NULL AND ${t.actorApiKeyId} IS NULL)`,
    ),
    check(
      'audit_event_api_key_actor_workspace_chk',
      sql`${t.actorType} <> 'api_key' OR ${t.workspaceId} IS NOT NULL`,
    ),
    check(
      'audit_event_channel_consistency_chk',
      sql`(${t.actorType} = 'user' AND ${t.actorChannel} IN ('web', 'mcp'))
          OR (${t.actorType} = 'api_key' AND ${t.actorChannel} IN ('api_key', 'mcp'))
          OR (${t.actorType} = 'system' AND ${t.actorChannel} = 'system')`,
    ),
    foreignKey({
      columns: [t.orgId, t.workspaceId],
      foreignColumns: [workspace.orgId, workspace.id],
      name: 'audit_event_org_workspace_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [t.workspaceId, t.actorApiKeyId],
      foreignColumns: [apiKey.workspaceId, apiKey.id],
      name: 'audit_event_actor_api_key_fk',
    }).onDelete('no action'),
    index('audit_event_org_created_idx').on(t.orgId, t.createdAt.desc()),
    index('audit_event_workspace_created_idx')
      .on(t.workspaceId, t.createdAt.desc())
      .where(sql`workspace_id IS NOT NULL`),
    index('audit_event_target_idx').on(t.targetType, t.targetId),
    index('audit_event_persona_action_created_idx').on(
      t.actorPersona,
      t.action,
      t.createdAt.desc(),
    ),
    index('audit_event_class_created_idx').on(t.eventClass, t.createdAt),
    index('audit_event_channel_action_created_idx').on(
      t.actorChannel,
      t.action,
      t.createdAt.desc(),
    ),
  ],
);

// ─────────────────────────────────────────────────────────────────────────
// 3.12 org_deletion_job (v6 new, v7 tightens status CHECK) — ops log that
//   survives org physical PURGE via snapshot columns. status × timestamp
//   integrity is enforced by org_deletion_job_status_chk.
// ─────────────────────────────────────────────────────────────────────────
export const orgDeletionJob = pgTable(
  'org_deletion_job',
  {
    id: uuid('id').primaryKey().default(uuidv7),
    orgId: uuid('org_id').references(() => org.id, { onDelete: 'set null' }),
    orgSlugSnapshot: text('org_slug_snapshot').notNull(),
    orgNameSnapshot: text('org_name_snapshot').notNull(),
    status: text('status').notNull(),
    requestedAt: timestamp('requested_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    startedAt: timestamp('started_at', { withTimezone: true }),
    completedAt: timestamp('completed_at', { withTimezone: true }),
    lastError: text('last_error'),
    progress: jsonb('progress').notNull().default(sql`'{}'::jsonb`),
    requestedActorType: text('requested_actor_type').notNull(),
    requestedActorId: uuid('requested_actor_id'),
  },
  (t) => [
    check(
      'org_deletion_job_slug_snapshot_length_chk',
      sql`length(${t.orgSlugSnapshot}) <= 63`,
    ),
    check(
      'org_deletion_job_name_snapshot_length_chk',
      sql`length(${t.orgNameSnapshot}) <= 120`,
    ),
    check(
      'org_deletion_job_last_error_length_chk',
      sql`${t.lastError} IS NULL OR length(${t.lastError}) <= 2000`,
    ),
    check(
      'org_deletion_job_status_chk',
      sql`(${t.status} = 'queued'
            AND ${t.startedAt} IS NULL
            AND ${t.completedAt} IS NULL
            AND ${t.lastError} IS NULL)
          OR (${t.status} = 'running'
            AND ${t.startedAt} IS NOT NULL
            AND ${t.completedAt} IS NULL
            AND ${t.lastError} IS NULL)
          OR (${t.status} = 'failed'
            AND ${t.startedAt} IS NOT NULL
            AND ${t.completedAt} IS NULL
            AND ${t.lastError} IS NOT NULL)
          OR (${t.status} = 'completed'
            AND ${t.startedAt} IS NOT NULL
            AND ${t.completedAt} IS NOT NULL
            AND ${t.lastError} IS NULL)`,
    ),
    check(
      'org_deletion_job_requested_actor_type_chk',
      sql`${t.requestedActorType} IN ('user', 'system')`,
    ),
    check(
      'org_deletion_job_requested_actor_consistency_chk',
      sql`(${t.requestedActorType} = 'user' AND ${t.requestedActorId} IS NOT NULL)
          OR (${t.requestedActorType} = 'system' AND ${t.requestedActorId} IS NULL)`,
    ),
    index('org_deletion_job_queued_idx')
      .on(t.requestedAt)
      .where(sql`status = 'queued'`),
    index('org_deletion_job_failed_idx')
      .on(t.requestedAt.desc())
      .where(sql`status = 'failed'`),
    index('org_deletion_job_org_id_idx')
      .on(t.orgId)
      .where(sql`org_id IS NOT NULL`),
    index('org_deletion_job_completed_at_idx')
      .on(t.completedAt.desc())
      .where(sql`completed_at IS NOT NULL`),
  ],
);

// ─────────────────────────────────────────────────────────────────────────
// 3.13 fact_definition — workspace-level business facts (data-connected
//   workspace MVP, see implementation_leverie_data_connected_workspace.md §3.1).
//   The (workspace_id, id) UNIQUE is the tenant-consistency composite-FK anchor
//   that logic_fact_binding uses. updated_at is stamped by the set_updated_at
//   trigger added in the migration (§3.0 convention 4), never by Drizzle.
// ─────────────────────────────────────────────────────────────────────────
export const factDefinition = pgTable(
  'fact_definition',
  {
    id: uuid('id').primaryKey().default(uuidv7),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspace.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    description: text('description'),
    type: text('type').notNull(),
    enumValues: jsonb('enum_values'),
    kind: text('kind').notNull(),
    aliases: jsonb('aliases').notNull().default(sql`'[]'::jsonb`),
    question: text('question'),
    sensitive: boolean('sensitive').notNull().default(false),
    loggingPolicy: text('logging_policy').notNull().default('full'),
    retentionPolicy: text('retention_policy')
      .notNull()
      .default('workspace_default'),
    status: text('status').notNull().default('active'),
    version: integer('version').notNull().default(1),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    createdActorType: text('created_actor_type').notNull(),
    createdActorId: uuid('created_actor_id'),
    updatedActorType: text('updated_actor_type'),
    updatedActorId: uuid('updated_actor_id'),
  },
  (t) => [
    check('fact_definition_name_length_chk', sql`length(${t.name}) <= 120`),
    check(
      'fact_definition_description_length_chk',
      sql`${t.description} IS NULL OR length(${t.description}) <= 1000`,
    ),
    check(
      'fact_definition_type_chk',
      sql`${t.type} IN ('string', 'number', 'bool', 'enum', 'date', 'datetime')`,
    ),
    check(
      'fact_definition_kind_chk',
      sql`${t.kind} IN ('key', 'system_fact', 'manual_fact', 'derived_fact', 'internal_fact')`,
    ),
    check(
      'fact_definition_status_chk',
      sql`${t.status} IN ('draft', 'active', 'deprecated')`,
    ),
    check(
      'fact_definition_logging_policy_chk',
      sql`${t.loggingPolicy} IN ('full', 'masked', 'hash', 'omit')`,
    ),
    check(
      'fact_definition_enum_values_type_chk',
      sql`${t.enumValues} IS NULL OR jsonb_typeof(${t.enumValues}) = 'array'`,
    ),
    check(
      'fact_definition_aliases_type_chk',
      sql`jsonb_typeof(${t.aliases}) = 'array'`,
    ),
    // enum facts require a non-empty enum value list
    check(
      'fact_definition_enum_values_required_chk',
      sql`${t.type} <> 'enum'
          OR (${t.enumValues} IS NOT NULL AND jsonb_array_length(${t.enumValues}) > 0)`,
    ),
    // active manual facts require a question
    check(
      'fact_definition_manual_question_chk',
      sql`${t.kind} <> 'manual_fact'
          OR ${t.status} <> 'active'
          OR length(btrim(coalesce(${t.question}, ''))) > 0`,
    ),
    check(
      'fact_definition_created_actor_type_chk',
      sql`${t.createdActorType} IN ('user', 'system')`,
    ),
    check(
      'fact_definition_updated_actor_type_chk',
      sql`${t.updatedActorType} IS NULL OR ${t.updatedActorType} IN ('user', 'system')`,
    ),
    check(
      'fact_definition_created_actor_consistency_chk',
      sql`(${t.createdActorType} = 'user' AND ${t.createdActorId} IS NOT NULL)
          OR (${t.createdActorType} = 'system' AND ${t.createdActorId} IS NULL)`,
    ),
    check(
      'fact_definition_updated_actor_consistency_chk',
      sql`(${t.updatedActorType} IS NULL AND ${t.updatedActorId} IS NULL)
          OR (${t.updatedActorType} = 'user' AND ${t.updatedActorId} IS NOT NULL)
          OR (${t.updatedActorType} = 'system' AND ${t.updatedActorId} IS NULL)`,
    ),
    // Composite-FK target so logic_fact_binding can enforce that a bound fact
    // lives in the same workspace as the binding (§3.0 convention 1).
    unique('fact_definition_workspace_id_id_uniq').on(t.workspaceId, t.id),
    // Unique active name per workspace. Deprecated rows are excluded so a name
    // can be reused after retirement. Alias uniqueness cannot be expressed in
    // SQL across JSON arrays and is enforced in route validation (§3.1).
    uniqueIndex('fact_definition_workspace_name_active_uniq')
      .on(t.workspaceId, sql`lower(${t.name})`)
      .where(sql`status <> 'deprecated'`),
    index('fact_definition_workspace_status_created_idx').on(
      t.workspaceId,
      t.status,
      t.createdAt.desc(),
    ),
    index('fact_definition_workspace_kind_status_idx').on(
      t.workspaceId,
      t.kind,
      t.status,
    ),
  ],
);

// ─────────────────────────────────────────────────────────────────────────
// 3.14 logic_fact_binding — maps engine field IDs to workspace facts without
//   changing Logic v2 (§3.2). The engine still evaluates by field ID; the
//   workspace resolves by fact ID and projects values into field IDs through
//   this binding. Both parents are referenced through tenant-consistency
//   composite FKs (§3.0 convention 1). updated_at uses the set_updated_at
//   trigger added in the migration.
// ─────────────────────────────────────────────────────────────────────────
export const logicFactBinding = pgTable(
  'logic_fact_binding',
  {
    id: uuid('id').primaryKey().default(uuidv7),
    workspaceId: uuid('workspace_id').notNull(),
    logicId: uuid('logic_id').notNull(),
    fieldId: text('field_id').notNull(),
    factId: uuid('fact_id').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    check(
      'logic_fact_binding_field_id_length_chk',
      sql`length(${t.fieldId}) <= 120`,
    ),
    // One fact per field and one field per fact within a logic (MVP, §3.2).
    unique('logic_fact_binding_logic_field_uniq').on(t.logicId, t.fieldId),
    unique('logic_fact_binding_logic_fact_uniq').on(t.logicId, t.factId),
    foreignKey({
      columns: [t.workspaceId, t.logicId],
      foreignColumns: [logic.workspaceId, logic.id],
      name: 'logic_fact_binding_workspace_logic_fk',
    }).onDelete('cascade'),
    // restrict so an in-use fact cannot be hard-deleted out from under a binding
    foreignKey({
      columns: [t.workspaceId, t.factId],
      foreignColumns: [factDefinition.workspaceId, factDefinition.id],
      name: 'logic_fact_binding_workspace_fact_fk',
    }).onDelete('restrict'),
    index('logic_fact_binding_logic_idx').on(t.logicId),
    index('logic_fact_binding_workspace_fact_idx').on(t.workspaceId, t.factId),
  ],
);

// ─────────────────────────────────────────────────────────────────────────
// 3.15 data_source — source metadata (§3.3). The stable entity; one row per
//   admin-facing source. MVP only allows kind='reference_table'. The
//   (workspace_id, id) UNIQUE is the composite-FK target for reference_table
//   and resolver_recipe. owner_user_id is NO ACTION DEFERRABLE (added in the
//   migration) so users are never physically deleted out from under a source.
// ─────────────────────────────────────────────────────────────────────────
export const dataSource = pgTable(
  'data_source',
  {
    id: uuid('id').primaryKey().default(uuidv7),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspace.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    kind: text('kind').notNull().default('reference_table'),
    schema: jsonb('schema').notNull(),
    schemaHash: text('schema_hash'),
    authType: text('auth_type').notNull().default('none'),
    secretRef: text('secret_ref'),
    allowedDomains: jsonb('allowed_domains'),
    // NO ACTION (DEFERRABLE INITIALLY IMMEDIATE added in the migration)
    ownerUserId: uuid('owner_user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'no action' }),
    status: text('status').notNull().default('active'),
    version: integer('version').notNull().default(1),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    createdActorType: text('created_actor_type').notNull(),
    createdActorId: uuid('created_actor_id'),
    updatedActorType: text('updated_actor_type'),
    updatedActorId: uuid('updated_actor_id'),
  },
  (t) => [
    check('data_source_name_length_chk', sql`length(${t.name}) <= 120`),
    check(
      'data_source_kind_chk',
      sql`${t.kind} IN ('reference_table', 'spreadsheet', 'managed_connector', 'openapi_http', 'graphql')`,
    ),
    check(
      'data_source_auth_type_chk',
      sql`${t.authType} IN ('none', 'api_key', 'bearer', 'basic', 'oauth')`,
    ),
    check(
      'data_source_status_chk',
      sql`${t.status} IN ('draft', 'active', 'disabled')`,
    ),
    check(
      'data_source_schema_object_chk',
      sql`jsonb_typeof(${t.schema}) = 'object'`,
    ),
    check(
      'data_source_allowed_domains_type_chk',
      sql`${t.allowedDomains} IS NULL OR jsonb_typeof(${t.allowedDomains}) = 'array'`,
    ),
    check(
      'data_source_created_actor_type_chk',
      sql`${t.createdActorType} IN ('user', 'system')`,
    ),
    check(
      'data_source_updated_actor_type_chk',
      sql`${t.updatedActorType} IS NULL OR ${t.updatedActorType} IN ('user', 'system')`,
    ),
    check(
      'data_source_created_actor_consistency_chk',
      sql`(${t.createdActorType} = 'user' AND ${t.createdActorId} IS NOT NULL)
          OR (${t.createdActorType} = 'system' AND ${t.createdActorId} IS NULL)`,
    ),
    check(
      'data_source_updated_actor_consistency_chk',
      sql`(${t.updatedActorType} IS NULL AND ${t.updatedActorId} IS NULL)
          OR (${t.updatedActorType} = 'user' AND ${t.updatedActorId} IS NOT NULL)
          OR (${t.updatedActorType} = 'system' AND ${t.updatedActorId} IS NULL)`,
    ),
    unique('data_source_workspace_id_id_uniq').on(t.workspaceId, t.id),
    index('data_source_workspace_status_idx').on(
      t.workspaceId,
      t.status,
      t.createdAt.desc(),
    ),
  ],
);

// ─────────────────────────────────────────────────────────────────────────
// 3.16 reference_table — one immutable version of the data under a data source
//   (§3.4). replace/append create a new version (version = previous + 1) and
//   flip the old one to 'superseded'; rows are kept for recorded replay. At
//   most one 'active' version per source (partial unique index).
// ─────────────────────────────────────────────────────────────────────────
export const referenceTable = pgTable(
  'reference_table',
  {
    id: uuid('id').primaryKey().default(uuidv7),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspace.id, { onDelete: 'cascade' }),
    dataSourceId: uuid('data_source_id').notNull(),
    name: text('name').notNull(),
    columns: jsonb('columns').notNull(),
    keyColumns: jsonb('key_columns').notNull(),
    rowCount: integer('row_count').notNull(),
    storageRef: text('storage_ref'),
    version: integer('version').notNull(),
    status: text('status').notNull().default('active'),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    createdActorType: text('created_actor_type').notNull(),
    createdActorId: uuid('created_actor_id'),
  },
  (t) => [
    check('reference_table_name_length_chk', sql`length(${t.name}) <= 120`),
    check(
      'reference_table_columns_type_chk',
      sql`jsonb_typeof(${t.columns}) = 'array'`,
    ),
    check(
      'reference_table_key_columns_type_chk',
      sql`jsonb_typeof(${t.keyColumns}) = 'array'`,
    ),
    check('reference_table_row_count_chk', sql`${t.rowCount} >= 0`),
    check(
      'reference_table_status_chk',
      sql`${t.status} IN ('active', 'superseded', 'disabled')`,
    ),
    check(
      'reference_table_created_actor_type_chk',
      sql`${t.createdActorType} IN ('user', 'system')`,
    ),
    check(
      'reference_table_created_actor_consistency_chk',
      sql`(${t.createdActorType} = 'user' AND ${t.createdActorId} IS NOT NULL)
          OR (${t.createdActorType} = 'system' AND ${t.createdActorId} IS NULL)`,
    ),
    foreignKey({
      columns: [t.workspaceId, t.dataSourceId],
      foreignColumns: [dataSource.workspaceId, dataSource.id],
      name: 'reference_table_workspace_source_fk',
    }).onDelete('cascade'),
    unique('reference_table_source_version_uniq').on(t.dataSourceId, t.version),
    unique('reference_table_workspace_id_id_uniq').on(t.workspaceId, t.id),
    uniqueIndex('reference_table_source_active_uniq')
      .on(t.dataSourceId)
      .where(sql`status = 'active'`),
    index('reference_table_workspace_idx').on(
      t.workspaceId,
      t.createdAt.desc(),
    ),
  ],
);

// ─────────────────────────────────────────────────────────────────────────
// 3.17 reference_table_row — rows for lookup (§3.5). key_hash is the hash of
//   the normalized key value(s) in configured key-column order. The unique
//   (reference_table_id, key_hash) is the first line of defense for the
//   "reject duplicate keys" upload policy (§6.4). No updated_at (rows are
//   immutable within a version), so no trigger.
// ─────────────────────────────────────────────────────────────────────────
export const referenceTableRow = pgTable(
  'reference_table_row',
  {
    id: uuid('id').primaryKey().default(uuidv7),
    referenceTableId: uuid('reference_table_id')
      .notNull()
      .references(() => referenceTable.id, { onDelete: 'cascade' }),
    rowIndex: integer('row_index').notNull(),
    keyHash: text('key_hash').notNull(),
    keyValues: jsonb('key_values').notNull(),
    data: jsonb('data').notNull(),
  },
  (t) => [
    uniqueIndex('reference_table_row_index_uniq').on(
      t.referenceTableId,
      t.rowIndex,
    ),
    uniqueIndex('reference_table_row_key_hash_uniq').on(
      t.referenceTableId,
      t.keyHash,
    ),
  ],
);

// ─────────────────────────────────────────────────────────────────────────
// 3.18 resolver_recipe — how facts are resolved from a data source (§3.6). The
//   recipe pins the stable data_source_id; the active reference_table version
//   is resolved at publish time and pinned in the snapshot. timeout/cache/
//   sensitivity policy columns are deferred until HTTP connectors arrive.
// ─────────────────────────────────────────────────────────────────────────
export const resolverRecipe = pgTable(
  'resolver_recipe',
  {
    id: uuid('id').primaryKey().default(uuidv7),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspace.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    inputFactIds: jsonb('input_fact_ids').notNull(),
    dataSourceId: uuid('data_source_id').notNull(),
    operationRef: jsonb('operation_ref').notNull(),
    parameterMappings: jsonb('parameter_mappings').notNull(),
    outputMappings: jsonb('output_mappings').notNull(),
    normalizers: jsonb('normalizers').notNull().default(sql`'{}'::jsonb`),
    fallbackPolicy: text('fallback_policy').notNull().default('ask_operator'),
    status: text('status').notNull().default('active'),
    version: integer('version').notNull().default(1),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    createdActorType: text('created_actor_type').notNull(),
    createdActorId: uuid('created_actor_id'),
    updatedActorType: text('updated_actor_type'),
    updatedActorId: uuid('updated_actor_id'),
  },
  (t) => [
    check('resolver_recipe_name_length_chk', sql`length(${t.name}) <= 120`),
    check(
      'resolver_recipe_input_fact_ids_type_chk',
      sql`jsonb_typeof(${t.inputFactIds}) = 'array'`,
    ),
    check(
      'resolver_recipe_operation_ref_type_chk',
      sql`jsonb_typeof(${t.operationRef}) = 'object'`,
    ),
    check(
      'resolver_recipe_parameter_mappings_type_chk',
      sql`jsonb_typeof(${t.parameterMappings}) = 'object'`,
    ),
    check(
      'resolver_recipe_output_mappings_type_chk',
      sql`jsonb_typeof(${t.outputMappings}) = 'array'`,
    ),
    check(
      'resolver_recipe_normalizers_type_chk',
      sql`jsonb_typeof(${t.normalizers}) = 'object'`,
    ),
    check(
      'resolver_recipe_fallback_policy_chk',
      sql`${t.fallbackPolicy} IN ('ask_operator', 'mark_unavailable', 'block')`,
    ),
    check(
      'resolver_recipe_status_chk',
      sql`${t.status} IN ('draft', 'active', 'disabled')`,
    ),
    check(
      'resolver_recipe_created_actor_type_chk',
      sql`${t.createdActorType} IN ('user', 'system')`,
    ),
    check(
      'resolver_recipe_updated_actor_type_chk',
      sql`${t.updatedActorType} IS NULL OR ${t.updatedActorType} IN ('user', 'system')`,
    ),
    check(
      'resolver_recipe_created_actor_consistency_chk',
      sql`(${t.createdActorType} = 'user' AND ${t.createdActorId} IS NOT NULL)
          OR (${t.createdActorType} = 'system' AND ${t.createdActorId} IS NULL)`,
    ),
    check(
      'resolver_recipe_updated_actor_consistency_chk',
      sql`(${t.updatedActorType} IS NULL AND ${t.updatedActorId} IS NULL)
          OR (${t.updatedActorType} = 'user' AND ${t.updatedActorId} IS NOT NULL)
          OR (${t.updatedActorType} = 'system' AND ${t.updatedActorId} IS NULL)`,
    ),
    foreignKey({
      columns: [t.workspaceId, t.dataSourceId],
      foreignColumns: [dataSource.workspaceId, dataSource.id],
      name: 'resolver_recipe_workspace_source_fk',
    }).onDelete('restrict'),
    unique('resolver_recipe_workspace_id_id_uniq').on(t.workspaceId, t.id),
    index('resolver_recipe_workspace_status_idx').on(
      t.workspaceId,
      t.status,
      t.createdAt.desc(),
    ),
  ],
);

// ─────────────────────────────────────────────────────────────────────────
// 3.19 logic_version_data_snapshot — data-layer references pinned at publish
//   time (§3.7). Single source of truth for the data definitions used by a
//   published version: bindings, fact definitions, resolver recipes, data
//   sources, and the concrete active reference_table id+version. snapshot_hash
//   is the bundle identity surfaced to operators/auditors as the "data
//   definition version" (it replaces the unsound max-active-version integers).
//   decision_session references this row rather than re-storing config.
// ─────────────────────────────────────────────────────────────────────────
export const logicVersionDataSnapshot = pgTable(
  'logic_version_data_snapshot',
  {
    id: uuid('id').primaryKey().default(uuidv7),
    workspaceId: uuid('workspace_id').notNull(),
    logicId: uuid('logic_id').notNull(),
    logicVersionId: uuid('logic_version_id').notNull(),
    bindings: jsonb('bindings').notNull(),
    factDefinitions: jsonb('fact_definitions').notNull(),
    resolverRecipes: jsonb('resolver_recipes').notNull(),
    dataSources: jsonb('data_sources').notNull(),
    referenceTables: jsonb('reference_tables').notNull(),
    snapshotHash: text('snapshot_hash').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    check(
      'lv_data_snapshot_bindings_type_chk',
      sql`jsonb_typeof(${t.bindings}) = 'array'`,
    ),
    check(
      'lv_data_snapshot_fact_definitions_type_chk',
      sql`jsonb_typeof(${t.factDefinitions}) = 'array'`,
    ),
    check(
      'lv_data_snapshot_resolver_recipes_type_chk',
      sql`jsonb_typeof(${t.resolverRecipes}) = 'array'`,
    ),
    check(
      'lv_data_snapshot_data_sources_type_chk',
      sql`jsonb_typeof(${t.dataSources}) = 'array'`,
    ),
    check(
      'lv_data_snapshot_reference_tables_type_chk',
      sql`jsonb_typeof(${t.referenceTables}) = 'array'`,
    ),
    // Exactly one snapshot per published version.
    unique('lv_data_snapshot_logic_version_id_uniq').on(t.logicVersionId),
    foreignKey({
      columns: [t.workspaceId, t.logicId, t.logicVersionId],
      foreignColumns: [
        logicVersion.workspaceId,
        logicVersion.logicId,
        logicVersion.id,
      ],
      name: 'lv_data_snapshot_version_fk',
    }).onDelete('cascade'),
  ],
);

// ─────────────────────────────────────────────────────────────────────────
// 3.20 case_context — short-lived intake context (§3.8). Stores only extracted
//   key candidates by default, not raw pasted text (data minimization, §11.4).
//   expires_at needs a periodic sweeper. created_by is NO ACTION DEFERRABLE
//   (added in the migration). No updated_at, so no trigger.
// ─────────────────────────────────────────────────────────────────────────
export const caseContext = pgTable(
  'case_context',
  {
    id: uuid('id').primaryKey().default(uuidv7),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspace.id, { onDelete: 'cascade' }),
    sourceKind: text('source_kind').notNull(),
    sourceRef: text('source_ref'),
    rawPayloadRef: text('raw_payload_ref'),
    extractedKeys: jsonb('extracted_keys').notNull().default(sql`'[]'::jsonb`),
    expiresAt: timestamp('expires_at', { withTimezone: true }),
    // NO ACTION (DEFERRABLE INITIALLY IMMEDIATE added in the migration)
    createdBy: uuid('created_by').references(() => user.id, {
      onDelete: 'no action',
    }),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    check(
      'case_context_source_kind_chk',
      sql`${t.sourceKind} IN ('manual_paste', 'url_query', 'clipboard', 'webhook', 'embed')`,
    ),
    check(
      'case_context_extracted_keys_type_chk',
      sql`jsonb_typeof(${t.extractedKeys}) = 'array'`,
    ),
    index('case_context_workspace_created_idx').on(
      t.workspaceId,
      t.createdAt.desc(),
    ),
    index('case_context_expires_idx')
      .on(t.expiresAt)
      .where(sql`expires_at IS NOT NULL`),
  ],
);

// ─────────────────────────────────────────────────────────────────────────
// Better Auth tables — session / account / verification.
//
// These are auth implementation detail and are not in the 12 production
// tables of design_p3_schema.md. user.id is uuid (uuidv7) per the production
// schema, so the FK columns here are uuid as well. session/account/
// verification keep Better Auth's default column shapes; the auth adapter maps
// Better Auth's default user fields into the production user table.
// ─────────────────────────────────────────────────────────────────────────
export const session = pgTable('session', {
  id: text('id').primaryKey(),
  userId: uuid('user_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
  token: text('token').notNull().unique(),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  ipAddress: text('ip_address'),
  userAgent: text('user_agent'),
  createdAt: timestamp('created_at', { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true })
    .notNull()
    .defaultNow(),
});

export const account = pgTable('account', {
  id: text('id').primaryKey(),
  userId: uuid('user_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
  accountId: text('account_id').notNull(),
  providerId: text('provider_id').notNull(),
  accessToken: text('access_token'),
  refreshToken: text('refresh_token'),
  idToken: text('id_token'),
  accessTokenExpiresAt: timestamp('access_token_expires_at', {
    withTimezone: true,
  }),
  refreshTokenExpiresAt: timestamp('refresh_token_expires_at', {
    withTimezone: true,
  }),
  scope: text('scope'),
  password: text('password'),
  createdAt: timestamp('created_at', { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true })
    .notNull()
    .defaultNow(),
});

export const verification = pgTable('verification', {
  id: text('id').primaryKey(),
  identifier: text('identifier').notNull(),
  value: text('value').notNull(),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true })
    .notNull()
    .defaultNow(),
});
