// P3.2.b — production Drizzle schema, translating [design_p3_schema.md v7] into
// drizzle-orm pgTable definitions. Twelve production tables (user / org /
// workspace / membership / invitation / logic / logic_version / api_key /
// api_key_logic_scope / execution_log / audit_event / org_deletion_job) plus
// Better Auth's session / account / verification.
//
// Drizzle covers most of the DDL natively. The following SQL DDL elements are
// emitted by hand in the generated initial migration because the Drizzle API
// has no clean expression for them:
//
//   1. `DEFERRABLE INITIALLY IMMEDIATE` on foreign keys. Drizzle's
//      `.onDelete("no action")` produces NO ACTION but cannot add the
//      DEFERRABLE modifier. The user / api_key / logic_version cross-table FKs
//      all need it (see [design_p3_schema.md §4 リレーション一覧]).
//   2. `CREATE EXTENSION` statements for `citext` / `pgcrypto`.
//   3. `BEFORE UPDATE` triggers that call `set_updated_at()`. Drizzle's
//      `.$onUpdate()` fires only when Drizzle is the writer; we need DB-level
//      triggers so raw SQL writes (psql, migrations) also stamp updated_at.
//   4. Some CHECK expressions that reference `jsonb_typeof(...)` or compound
//      multi-column conditions can be expressed via Drizzle's `check()`, but
//      we keep them here for documentation parity with design_p3_schema.md.
//
// Better Auth is reconciled with the production user shape in apps/api/src/auth.ts:
// user.id is generated by the DB uuidv7() default, emailVerified maps to
// email_verified_at, and last_login_at / deleted_at are maintained by auth hooks.

import { sql } from 'drizzle-orm';
import {
  check,
  customType,
  foreignKey,
  index,
  integer,
  jsonb,
  pgTable,
  primaryKey,
  text,
  timestamp,
  unique,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core';

// citext is inlined here (rather than imported from ./types.ts) because
// drizzle-kit's schema loader does its own module resolution that does not
// honor our tsconfig's `moduleResolution: bundler`, so `./types.js` fails to
// resolve to types.ts at generation time. The helper is one-line so the
// inline cost is trivial.
const citext = customType<{ data: string; driverData: string }>({
  dataType() {
    return 'citext';
  },
});

const uuidv7 = sql`uuidv7()`;

// ─────────────────────────────────────────────────────────────────────────
// 3.1 user — global identity. Physical delete is blocked; we redact + set
//   deleted_at. All cross-table FKs to user are NO ACTION DEFERRABLE so
//   `DELETE FROM "user"` raises rather than orphaning rows.
// ─────────────────────────────────────────────────────────────────────────
export const user = pgTable(
  'user',
  {
    id: uuid('id').primaryKey().default(uuidv7),
    email: citext('email').notNull(),
    name: text('name').notNull(),
    image: text('image'),
    emailVerifiedAt: timestamp('email_verified_at', { withTimezone: true }),
    lastLoginAt: timestamp('last_login_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    deletedAt: timestamp('deleted_at', { withTimezone: true }),
  },
  (t) => [uniqueIndex('user_email_uniq').on(t.email)],
);

// ─────────────────────────────────────────────────────────────────────────
// 3.2 org — tenant root. lifecycle_status / deleted_at / purge_requested_at
//   are tied by `org_lifecycle_consistency_chk` (v7). Slug uniqueness holds
//   until physical PURGE so the 30-day recovery window keeps URLs working.
// ─────────────────────────────────────────────────────────────────────────
export const org = pgTable(
  'org',
  {
    id: uuid('id').primaryKey().default(uuidv7),
    slug: text('slug').notNull(),
    name: text('name').notNull(),
    plan: text('plan').notNull().default('free'),
    lifecycleStatus: text('lifecycle_status').notNull().default('active'),
    purgeRequestedAt: timestamp('purge_requested_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    deletedAt: timestamp('deleted_at', { withTimezone: true }),
    createdActorType: text('created_actor_type').notNull(),
    createdActorId: uuid('created_actor_id'),
    updatedActorType: text('updated_actor_type'),
    updatedActorId: uuid('updated_actor_id'),
  },
  (t) => [
    check(
      'org_slug_format_chk',
      sql`${t.slug} ~ '^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$'`,
    ),
    check(
      'org_lifecycle_status_chk',
      sql`${t.lifecycleStatus} IN ('active', 'deleting', 'purging')`,
    ),
    check(
      'org_lifecycle_consistency_chk',
      sql`(
        ${t.lifecycleStatus} = 'active'
        AND ${t.deletedAt} IS NULL
        AND ${t.purgeRequestedAt} IS NULL
      ) OR (
        ${t.lifecycleStatus} IN ('deleting', 'purging')
        AND ${t.deletedAt} IS NOT NULL
        AND ${t.purgeRequestedAt} IS NOT NULL
      )`,
    ),
    check(
      'org_created_actor_type_chk',
      sql`${t.createdActorType} IN ('user', 'system')`,
    ),
    check(
      'org_updated_actor_type_chk',
      sql`${t.updatedActorType} IS NULL OR ${t.updatedActorType} IN ('user', 'system')`,
    ),
    check(
      'org_created_actor_consistency_chk',
      sql`(${t.createdActorType} = 'user' AND ${t.createdActorId} IS NOT NULL)
          OR (${t.createdActorType} = 'system' AND ${t.createdActorId} IS NULL)`,
    ),
    check(
      'org_updated_actor_consistency_chk',
      sql`(${t.updatedActorType} IS NULL AND ${t.updatedActorId} IS NULL)
          OR (${t.updatedActorType} = 'user' AND ${t.updatedActorId} IS NOT NULL)
          OR (${t.updatedActorType} = 'system' AND ${t.updatedActorId} IS NULL)`,
    ),
    uniqueIndex('org_slug_not_purged_uniq')
      .on(t.slug)
      .where(sql`lifecycle_status IN ('active', 'deleting', 'purging')`),
    index('org_lifecycle_purge_queue_idx')
      .on(t.purgeRequestedAt)
      .where(sql`lifecycle_status IN ('deleting', 'purging')`),
  ],
);

// ─────────────────────────────────────────────────────────────────────────
// 3.3 workspace — project-scope under org. The (org_id, id) UNIQUE is the
//   composite-FK anchor that audit_event uses to enforce org/workspace
//   consistency.
// ─────────────────────────────────────────────────────────────────────────
export const workspace = pgTable(
  'workspace',
  {
    id: uuid('id').primaryKey().default(uuidv7),
    orgId: uuid('org_id')
      .notNull()
      .references(() => org.id, { onDelete: 'cascade' }),
    slug: text('slug').notNull(),
    name: text('name').notNull(),
    description: text('description'),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    deletedAt: timestamp('deleted_at', { withTimezone: true }),
    createdActorType: text('created_actor_type').notNull(),
    createdActorId: uuid('created_actor_id'),
    updatedActorType: text('updated_actor_type'),
    updatedActorId: uuid('updated_actor_id'),
  },
  (t) => [
    check(
      'workspace_slug_format_chk',
      sql`${t.slug} ~ '^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$'`,
    ),
    check(
      'workspace_created_actor_type_chk',
      sql`${t.createdActorType} IN ('user', 'system')`,
    ),
    check(
      'workspace_updated_actor_type_chk',
      sql`${t.updatedActorType} IS NULL OR ${t.updatedActorType} IN ('user', 'system')`,
    ),
    check(
      'workspace_created_actor_consistency_chk',
      sql`(${t.createdActorType} = 'user' AND ${t.createdActorId} IS NOT NULL)
          OR (${t.createdActorType} = 'system' AND ${t.createdActorId} IS NULL)`,
    ),
    check(
      'workspace_updated_actor_consistency_chk',
      sql`(${t.updatedActorType} IS NULL AND ${t.updatedActorId} IS NULL)
          OR (${t.updatedActorType} = 'user' AND ${t.updatedActorId} IS NOT NULL)
          OR (${t.updatedActorType} = 'system' AND ${t.updatedActorId} IS NULL)`,
    ),
    // Composite UNIQUE constraint (not a partial unique index) because it
    // serves as the FK target for audit_event(org_id, workspace_id). UNIQUE
    // CONSTRAINTs are emitted inside CREATE TABLE so they're available before
    // any subsequent ALTER TABLE ADD FOREIGN KEY runs in the same migration.
    unique('workspace_org_id_id_uniq').on(t.orgId, t.id),
    uniqueIndex('workspace_org_slug_active_uniq')
      .on(t.orgId, t.slug)
      .where(sql`deleted_at IS NULL`),
    index('workspace_org_id_active_idx')
      .on(t.orgId, t.createdAt.desc())
      .where(sql`deleted_at IS NULL`),
  ],
);

// ─────────────────────────────────────────────────────────────────────────
// 3.4 membership — user × org with role. user_id FK is NO ACTION DEFERRABLE
//   (v7) to block user physical deletion at the DB level. Lifecycle is
//   accept-only: active rows have removed_at = NULL.
// ─────────────────────────────────────────────────────────────────────────
export const membership = pgTable(
  'membership',
  {
    id: uuid('id').primaryKey().default(uuidv7),
    orgId: uuid('org_id')
      .notNull()
      .references(() => org.id, { onDelete: 'cascade' }),
    // v7: NO ACTION (DEFERRABLE INITIALLY IMMEDIATE is added in the initial migration)
    userId: uuid('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'no action' }),
    role: text('role').notNull(),
    invitedActorType: text('invited_actor_type').notNull(),
    invitedActorId: uuid('invited_actor_id'),
    invitedAt: timestamp('invited_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    joinedAt: timestamp('joined_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    removedAt: timestamp('removed_at', { withTimezone: true }),
  },
  (t) => [
    check(
      'membership_role_chk',
      sql`${t.role} IN ('owner', 'admin', 'editor', 'viewer', 'runner')`,
    ),
    check(
      'membership_invited_actor_type_chk',
      sql`${t.invitedActorType} IN ('user', 'system')`,
    ),
    check(
      'membership_invited_actor_consistency_chk',
      sql`(${t.invitedActorType} = 'user' AND ${t.invitedActorId} IS NOT NULL)
          OR (${t.invitedActorType} = 'system' AND ${t.invitedActorId} IS NULL)`,
    ),
    uniqueIndex('membership_org_user_not_removed_uniq')
      .on(t.orgId, t.userId)
      .where(sql`removed_at IS NULL`),
    index('membership_user_not_removed_idx')
      .on(t.userId)
      .where(sql`removed_at IS NULL`),
  ],
);

// ─────────────────────────────────────────────────────────────────────────
// 3.5 invitation — pending → accepted XOR revoked. v6 adds CHECK to block
//   late accepts (accepted_at <= expires_at).
// ─────────────────────────────────────────────────────────────────────────
export const invitation = pgTable(
  'invitation',
  {
    id: uuid('id').primaryKey().default(uuidv7),
    orgId: uuid('org_id')
      .notNull()
      .references(() => org.id, { onDelete: 'cascade' }),
    email: citext('email').notNull(),
    role: text('role').notNull(),
    tokenDigest: text('token_digest').notNull(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    acceptedAt: timestamp('accepted_at', { withTimezone: true }),
    revokedAt: timestamp('revoked_at', { withTimezone: true }),
    invitedActorType: text('invited_actor_type').notNull(),
    invitedActorId: uuid('invited_actor_id'),
    acceptedActorType: text('accepted_actor_type'),
    acceptedActorId: uuid('accepted_actor_id'),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    check(
      'invitation_role_chk',
      sql`${t.role} IN ('owner', 'admin', 'editor', 'viewer', 'runner')`,
    ),
    check(
      'invitation_invited_actor_type_chk',
      sql`${t.invitedActorType} IN ('user', 'system')`,
    ),
    check(
      'invitation_accepted_actor_type_chk',
      sql`${t.acceptedActorType} IS NULL OR ${t.acceptedActorType} IN ('user', 'system')`,
    ),
    check(
      'invitation_terminal_state_chk',
      sql`${t.acceptedAt} IS NULL OR ${t.revokedAt} IS NULL`,
    ),
    check(
      'invitation_accept_before_expiry_chk',
      sql`${t.acceptedAt} IS NULL OR ${t.acceptedAt} <= ${t.expiresAt}`,
    ),
    check(
      'invitation_accepted_pair_chk',
      sql`(${t.acceptedAt} IS NULL
            AND ${t.acceptedActorType} IS NULL
            AND ${t.acceptedActorId} IS NULL)
          OR (${t.acceptedAt} IS NOT NULL
            AND ${t.acceptedActorType} IS NOT NULL
            AND (
              (${t.acceptedActorType} = 'user' AND ${t.acceptedActorId} IS NOT NULL)
              OR (${t.acceptedActorType} = 'system' AND ${t.acceptedActorId} IS NULL)
            ))`,
    ),
    check(
      'invitation_invited_actor_consistency_chk',
      sql`(${t.invitedActorType} = 'user' AND ${t.invitedActorId} IS NOT NULL)
          OR (${t.invitedActorType} = 'system' AND ${t.invitedActorId} IS NULL)`,
    ),
    uniqueIndex('invitation_token_digest_uniq').on(t.tokenDigest),
    uniqueIndex('invitation_org_email_open_uniq')
      .on(t.orgId, t.email)
      .where(sql`accepted_at IS NULL AND revoked_at IS NULL`),
    index('invitation_email_open_idx')
      .on(t.email)
      .where(sql`accepted_at IS NULL AND revoked_at IS NULL`),
  ],
);

// ─────────────────────────────────────────────────────────────────────────
// 3.6 logic — draft + production pin. production_version_id is a composite FK
//   to logic_version, added in the initial migration after both tables
//   exist (circular dependency).
// ─────────────────────────────────────────────────────────────────────────
export const logic = pgTable(
  'logic',
  {
    id: uuid('id').primaryKey().default(uuidv7),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspace.id, { onDelete: 'cascade' }),
    slug: text('slug').notNull(),
    name: text('name').notNull(),
    description: text('description'),
    draftData: jsonb('draft_data').notNull(),
    draftSchemaVersion: text('draft_schema_version').notNull().default('2'),
    draftRevision: integer('draft_revision').notNull().default(0),
    productionVersionId: uuid('production_version_id'),
    draftUpdatedAt: timestamp('draft_updated_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    draftUpdatedActorType: text('draft_updated_actor_type').notNull(),
    draftUpdatedActorId: uuid('draft_updated_actor_id'),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    deletedAt: timestamp('deleted_at', { withTimezone: true }),
    createdActorType: text('created_actor_type').notNull(),
    createdActorId: uuid('created_actor_id'),
    updatedActorType: text('updated_actor_type'),
    updatedActorId: uuid('updated_actor_id'),
  },
  (t) => [
    check(
      'logic_slug_format_chk',
      sql`${t.slug} ~ '^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$'`,
    ),
    check(
      'logic_draft_schema_version_matches_chk',
      sql`jsonb_typeof(${t.draftData}->'version') = 'string'
          AND ${t.draftSchemaVersion} = ${t.draftData}->>'version'`,
    ),
    check(
      'logic_created_actor_type_chk',
      sql`${t.createdActorType} IN ('user', 'system')`,
    ),
    check(
      'logic_updated_actor_type_chk',
      sql`${t.updatedActorType} IS NULL OR ${t.updatedActorType} IN ('user', 'api_key', 'system')`,
    ),
    check(
      'logic_draft_updated_actor_type_chk',
      sql`${t.draftUpdatedActorType} IN ('user', 'system')`,
    ),
    check(
      'logic_created_actor_consistency_chk',
      sql`(${t.createdActorType} = 'user' AND ${t.createdActorId} IS NOT NULL)
          OR (${t.createdActorType} = 'system' AND ${t.createdActorId} IS NULL)`,
    ),
    check(
      'logic_updated_actor_consistency_chk',
      sql`(${t.updatedActorType} IS NULL AND ${t.updatedActorId} IS NULL)
          OR (${t.updatedActorType} IN ('user', 'api_key') AND ${t.updatedActorId} IS NOT NULL)
          OR (${t.updatedActorType} = 'system' AND ${t.updatedActorId} IS NULL)`,
    ),
    check(
      'logic_draft_updated_actor_consistency_chk',
      sql`(${t.draftUpdatedActorType} = 'user' AND ${t.draftUpdatedActorId} IS NOT NULL)
          OR (${t.draftUpdatedActorType} = 'system' AND ${t.draftUpdatedActorId} IS NULL)`,
    ),
    // FK target for execution_log / api_key_logic_scope — see workspace
    // comment above for why this is a UNIQUE CONSTRAINT, not an index.
    unique('logic_workspace_id_id_uniq').on(t.workspaceId, t.id),
    uniqueIndex('logic_workspace_slug_active_uniq')
      .on(t.workspaceId, t.slug)
      .where(sql`deleted_at IS NULL`),
    index('logic_workspace_active_idx')
      .on(t.workspaceId, t.draftUpdatedAt.desc())
      .where(sql`deleted_at IS NULL`),
  ],
);

// ─────────────────────────────────────────────────────────────────────────
// 3.7 logic_version — immutable snapshots. The 3-tuple (logic_id, id,
//   version_number) UNIQUE is the anchor for execution_log's composite FK.
// ─────────────────────────────────────────────────────────────────────────
export const logicVersion = pgTable(
  'logic_version',
  {
    id: uuid('id').primaryKey().default(uuidv7),
    logicId: uuid('logic_id')
      .notNull()
      .references(() => logic.id, { onDelete: 'cascade' }),
    versionNumber: integer('version_number').notNull(),
    schemaVersion: text('schema_version').notNull().default('2'),
    data: jsonb('data').notNull(),
    releaseNotes: text('release_notes'),
    publishedAt: timestamp('published_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    publishedActorType: text('published_actor_type').notNull(),
    publishedActorId: uuid('published_actor_id'),
  },
  (t) => [
    check(
      'logic_version_version_number_positive_chk',
      sql`${t.versionNumber} > 0`,
    ),
    check(
      'logic_version_schema_version_matches_chk',
      sql`jsonb_typeof(${t.data}->'version') = 'string'
          AND ${t.schemaVersion} = ${t.data}->>'version'`,
    ),
    check(
      'logic_version_published_actor_type_chk',
      sql`${t.publishedActorType} IN ('user', 'system')`,
    ),
    check(
      'logic_version_published_actor_consistency_chk',
      sql`(${t.publishedActorType} = 'user' AND ${t.publishedActorId} IS NOT NULL)
          OR (${t.publishedActorType} = 'system' AND ${t.publishedActorId} IS NULL)`,
    ),
    unique('logic_version_logic_number_uniq').on(t.logicId, t.versionNumber),
    // FK target for logic.production_version_id composite FK (added in
    // the initial migration).
    unique('logic_version_logic_id_id_uniq').on(t.logicId, t.id),
    // FK target for execution_log's 3-tuple composite FK.
    unique('logic_version_logic_id_id_number_uniq').on(
      t.logicId,
      t.id,
      t.versionNumber,
    ),
    index('logic_version_logic_id_desc_idx').on(
      t.logicId,
      t.versionNumber.desc(),
    ),
  ],
);

// ─────────────────────────────────────────────────────────────────────────
// 3.8 api_key — HMAC lookup + argon2 verify. v6 adds lookup_secret_version
//   for HMAC server-secret rotation.
// ─────────────────────────────────────────────────────────────────────────
export const apiKey = pgTable(
  'api_key',
  {
    id: uuid('id').primaryKey().default(uuidv7),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspace.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    lookupSecretVersion: text('lookup_secret_version').notNull().default('v1'),
    lookupDigest: text('lookup_digest').notNull(),
    keyHash: text('key_hash').notNull(),
    keyPrefix: text('key_prefix').notNull(),
    role: text('role').notNull(),
    scopeMode: text('scope_mode').notNull().default('all'),
    expiresAt: timestamp('expires_at', { withTimezone: true }),
    lastUsedAt: timestamp('last_used_at', { withTimezone: true }),
    revokedAt: timestamp('revoked_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    createdActorType: text('created_actor_type').notNull(),
    createdActorId: uuid('created_actor_id'),
  },
  (t) => [
    check('api_key_role_chk', sql`${t.role} IN ('editor', 'viewer', 'runner')`),
    check(
      'api_key_scope_mode_chk',
      sql`${t.scopeMode} IN ('all', 'allowlist')`,
    ),
    check(
      'api_key_created_actor_type_chk',
      sql`${t.createdActorType} IN ('user', 'system')`,
    ),
    check(
      'api_key_created_actor_consistency_chk',
      sql`(${t.createdActorType} = 'user' AND ${t.createdActorId} IS NOT NULL)
          OR (${t.createdActorType} = 'system' AND ${t.createdActorId} IS NULL)`,
    ),
    // FK target for api_key_logic_scope / execution_log / audit_event
    // composite FKs — same reason as workspace.orgIdIdUniq above.
    unique('api_key_workspace_id_id_uniq').on(t.workspaceId, t.id),
    uniqueIndex('api_key_lookup_digest_uniq').on(
      t.lookupSecretVersion,
      t.lookupDigest,
    ),
    index('api_key_workspace_not_revoked_idx')
      .on(t.workspaceId, t.createdAt.desc())
      .where(sql`revoked_at IS NULL`),
  ],
);

// ─────────────────────────────────────────────────────────────────────────
// 3.9 api_key_logic_scope — allowlist join. Composite PK is tenant-prefixed.
// ─────────────────────────────────────────────────────────────────────────
export const apiKeyLogicScope = pgTable(
  'api_key_logic_scope',
  {
    workspaceId: uuid('workspace_id').notNull(),
    apiKeyId: uuid('api_key_id').notNull(),
    logicId: uuid('logic_id').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    primaryKey({ columns: [t.workspaceId, t.apiKeyId, t.logicId] }),
    foreignKey({
      columns: [t.workspaceId, t.apiKeyId],
      foreignColumns: [apiKey.workspaceId, apiKey.id],
      name: 'api_key_logic_scope_api_key_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [t.workspaceId, t.logicId],
      foreignColumns: [logic.workspaceId, logic.id],
      name: 'api_key_logic_scope_logic_fk',
    }).onDelete('cascade'),
    index('api_key_logic_scope_workspace_logic_idx').on(
      t.workspaceId,
      t.logicId,
    ),
  ],
);

// ─────────────────────────────────────────────────────────────────────────
// 3.10 execution_log — every evaluate() call. v6 splits caller into
//   (actor_type × channel). The 3-tuple FK to logic_version is NO ACTION
//   DEFERRABLE (added in the initial migration).
// ─────────────────────────────────────────────────────────────────────────
export const executionLog = pgTable(
  'execution_log',
  {
    id: uuid('id').primaryKey().default(uuidv7),
    workspaceId: uuid('workspace_id').notNull(),
    logicId: uuid('logic_id').notNull(),
    logicVersionId: uuid('logic_version_id'),
    requestedVersionType: text('requested_version_type').notNull(),
    requestedVersionNumber: integer('requested_version_number'),
    resolvedVersionNumber: integer('resolved_version_number'),
    inputs: jsonb('inputs'),
    result: jsonb('result'),
    trace: jsonb('trace'),
    status: text('status').notNull(),
    callerActorType: text('caller_actor_type').notNull(),
    callerChannel: text('caller_channel').notNull(),
    // user FK is NO ACTION (DEFERRABLE added in the initial migration)
    callerUserId: uuid('caller_user_id').references(() => user.id, {
      onDelete: 'no action',
    }),
    callerApiKeyId: uuid('caller_api_key_id'),
    errorCode: text('error_code'),
    requestId: text('request_id'),
    latencyMs: integer('latency_ms').notNull(),
    errorMessage: text('error_message'),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    check(
      'execution_log_requested_version_type_chk',
      sql`${t.requestedVersionType} IN ('draft', 'latest', 'production', 'version')`,
    ),
    check(
      'execution_log_requested_version_number_positive_chk',
      sql`${t.requestedVersionNumber} IS NULL OR ${t.requestedVersionNumber} > 0`,
    ),
    check(
      'execution_log_resolved_version_number_positive_chk',
      sql`${t.resolvedVersionNumber} IS NULL OR ${t.resolvedVersionNumber} > 0`,
    ),
    check(
      'execution_log_status_chk',
      sql`${t.status} IN ('ok', 'no_match', 'error')`,
    ),
    check(
      'execution_log_caller_actor_type_chk',
      sql`${t.callerActorType} IN ('user', 'api_key', 'system')`,
    ),
    check(
      'execution_log_caller_channel_chk',
      sql`${t.callerChannel} IN ('web', 'api_key', 'mcp', 'system')`,
    ),
    check(
      'execution_log_latency_ms_non_negative_chk',
      sql`${t.latencyMs} >= 0`,
    ),
    check(
      'execution_log_status_payload_chk',
      sql`(${t.status} IN ('ok', 'no_match')
            AND ${t.inputs} IS NOT NULL
            AND ${t.result} IS NOT NULL
            AND ${t.trace} IS NOT NULL
            AND ${t.errorMessage} IS NULL
            AND ${t.errorCode} IS NULL)
          OR (${t.status} = 'error'
            AND ${t.result} IS NULL
            AND ${t.trace} IS NULL
            AND ${t.errorMessage} IS NOT NULL)`,
    ),
    check(
      'execution_log_requested_version_chk',
      sql`(${t.requestedVersionType} = 'draft'
            AND ${t.logicVersionId} IS NULL
            AND ${t.requestedVersionNumber} IS NULL
            AND ${t.resolvedVersionNumber} IS NULL)
          OR (${t.requestedVersionType} IN ('latest', 'production')
            AND ${t.logicVersionId} IS NOT NULL
            AND ${t.requestedVersionNumber} IS NULL
            AND ${t.resolvedVersionNumber} IS NOT NULL)
          OR (${t.requestedVersionType} = 'version'
            AND ${t.logicVersionId} IS NOT NULL
            AND ${t.requestedVersionNumber} IS NOT NULL
            AND ${t.resolvedVersionNumber} IS NOT NULL
            AND ${t.requestedVersionNumber} = ${t.resolvedVersionNumber})`,
    ),
    check(
      'execution_log_caller_chk',
      sql`(${t.callerActorType} = 'user'
            AND ${t.callerChannel} = 'web'
            AND ${t.callerUserId} IS NOT NULL
            AND ${t.callerApiKeyId} IS NULL)
          OR (${t.callerActorType} = 'api_key'
            AND ${t.callerChannel} IN ('api_key', 'mcp')
            AND ${t.callerUserId} IS NULL
            AND ${t.callerApiKeyId} IS NOT NULL)
          OR (${t.callerActorType} = 'system'
            AND ${t.callerChannel} = 'system'
            AND ${t.callerUserId} IS NULL
            AND ${t.callerApiKeyId} IS NULL)`,
    ),
    foreignKey({
      columns: [t.workspaceId, t.logicId],
      foreignColumns: [logic.workspaceId, logic.id],
      name: 'execution_log_workspace_logic_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [t.logicId, t.logicVersionId, t.resolvedVersionNumber],
      foreignColumns: [
        logicVersion.logicId,
        logicVersion.id,
        logicVersion.versionNumber,
      ],
      name: 'execution_log_version_tuple_fk',
    }).onDelete('no action'),
    foreignKey({
      columns: [t.workspaceId, t.callerApiKeyId],
      foreignColumns: [apiKey.workspaceId, apiKey.id],
      name: 'execution_log_caller_api_key_fk',
    }).onDelete('no action'),
    index('execution_log_logic_created_idx').on(t.logicId, t.createdAt.desc()),
    index('execution_log_workspace_created_idx').on(
      t.workspaceId,
      t.createdAt.desc(),
    ),
    index('execution_log_created_at_idx').on(t.createdAt),
    index('execution_log_workspace_requested_type_created_idx').on(
      t.workspaceId,
      t.requestedVersionType,
      t.createdAt.desc(),
    ),
    index('execution_log_request_id_idx')
      .on(t.requestId)
      .where(sql`request_id IS NOT NULL`),
    index('execution_log_error_code_created_idx')
      .on(t.errorCode, t.createdAt.desc())
      .where(sql`error_code IS NOT NULL`),
    index('execution_log_workspace_channel_created_idx').on(
      t.workspaceId,
      t.callerChannel,
      t.createdAt.desc(),
    ),
  ],
);

// ─────────────────────────────────────────────────────────────────────────
// 3.11 audit_event — security/product/system events. Separate retention per
//   event_class (security ≥ 1 year). actor_user_id FK is NO ACTION
//   DEFERRABLE (added in the initial migration).
// ─────────────────────────────────────────────────────────────────────────
export const auditEvent = pgTable(
  'audit_event',
  {
    id: uuid('id').primaryKey().default(uuidv7),
    orgId: uuid('org_id')
      .notNull()
      .references(() => org.id, { onDelete: 'cascade' }),
    workspaceId: uuid('workspace_id'),
    eventClass: text('event_class').notNull(),
    actorType: text('actor_type').notNull(),
    actorUserId: uuid('actor_user_id').references(() => user.id, {
      onDelete: 'no action',
    }),
    actorApiKeyId: uuid('actor_api_key_id'),
    actorPersona: text('actor_persona').notNull().default('unknown'),
    actorChannel: text('actor_channel').notNull(),
    action: text('action').notNull(),
    targetType: text('target_type').notNull(),
    targetId: uuid('target_id'),
    metadata: jsonb('metadata').notNull().default(sql`'{}'::jsonb`),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    check(
      'audit_event_event_class_chk',
      sql`${t.eventClass} IN ('security', 'product', 'system')`,
    ),
    check(
      'audit_event_actor_type_chk',
      sql`${t.actorType} IN ('user', 'api_key', 'system')`,
    ),
    check(
      'audit_event_actor_persona_chk',
      sql`${t.actorPersona} IN ('installer', 'author', 'unknown')`,
    ),
    check(
      'audit_event_actor_channel_chk',
      sql`${t.actorChannel} IN ('web', 'api_key', 'mcp', 'system')`,
    ),
    check(
      'audit_event_actor_consistency_chk',
      sql`(${t.actorType} = 'user' AND ${t.actorUserId} IS NOT NULL AND ${t.actorApiKeyId} IS NULL)
          OR (${t.actorType} = 'api_key' AND ${t.actorUserId} IS NULL AND ${t.actorApiKeyId} IS NOT NULL)
          OR (${t.actorType} = 'system' AND ${t.actorUserId} IS NULL AND ${t.actorApiKeyId} IS NULL)`,
    ),
    check(
      'audit_event_api_key_actor_workspace_chk',
      sql`${t.actorType} <> 'api_key' OR ${t.workspaceId} IS NOT NULL`,
    ),
    check(
      'audit_event_channel_consistency_chk',
      sql`(${t.actorType} = 'user' AND ${t.actorChannel} IN ('web', 'mcp'))
          OR (${t.actorType} = 'api_key' AND ${t.actorChannel} IN ('api_key', 'mcp'))
          OR (${t.actorType} = 'system' AND ${t.actorChannel} = 'system')`,
    ),
    foreignKey({
      columns: [t.orgId, t.workspaceId],
      foreignColumns: [workspace.orgId, workspace.id],
      name: 'audit_event_org_workspace_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [t.workspaceId, t.actorApiKeyId],
      foreignColumns: [apiKey.workspaceId, apiKey.id],
      name: 'audit_event_actor_api_key_fk',
    }).onDelete('no action'),
    index('audit_event_org_created_idx').on(t.orgId, t.createdAt.desc()),
    index('audit_event_workspace_created_idx')
      .on(t.workspaceId, t.createdAt.desc())
      .where(sql`workspace_id IS NOT NULL`),
    index('audit_event_target_idx').on(t.targetType, t.targetId),
    index('audit_event_persona_action_created_idx').on(
      t.actorPersona,
      t.action,
      t.createdAt.desc(),
    ),
    index('audit_event_class_created_idx').on(t.eventClass, t.createdAt),
    index('audit_event_channel_action_created_idx').on(
      t.actorChannel,
      t.action,
      t.createdAt.desc(),
    ),
  ],
);

// ─────────────────────────────────────────────────────────────────────────
// 3.12 org_deletion_job (v6 new, v7 tightens status CHECK) — ops log that
//   survives org physical PURGE via snapshot columns. status × timestamp
//   integrity is enforced by org_deletion_job_status_chk.
// ─────────────────────────────────────────────────────────────────────────
export const orgDeletionJob = pgTable(
  'org_deletion_job',
  {
    id: uuid('id').primaryKey().default(uuidv7),
    orgId: uuid('org_id').references(() => org.id, { onDelete: 'set null' }),
    orgSlugSnapshot: text('org_slug_snapshot').notNull(),
    orgNameSnapshot: text('org_name_snapshot').notNull(),
    status: text('status').notNull(),
    requestedAt: timestamp('requested_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    startedAt: timestamp('started_at', { withTimezone: true }),
    completedAt: timestamp('completed_at', { withTimezone: true }),
    lastError: text('last_error'),
    progress: jsonb('progress').notNull().default(sql`'{}'::jsonb`),
    requestedActorType: text('requested_actor_type').notNull(),
    requestedActorId: uuid('requested_actor_id'),
  },
  (t) => [
    check(
      'org_deletion_job_status_chk',
      sql`(${t.status} = 'queued'
            AND ${t.startedAt} IS NULL
            AND ${t.completedAt} IS NULL
            AND ${t.lastError} IS NULL)
          OR (${t.status} = 'running'
            AND ${t.startedAt} IS NOT NULL
            AND ${t.completedAt} IS NULL
            AND ${t.lastError} IS NULL)
          OR (${t.status} = 'failed'
            AND ${t.startedAt} IS NOT NULL
            AND ${t.completedAt} IS NULL
            AND ${t.lastError} IS NOT NULL)
          OR (${t.status} = 'completed'
            AND ${t.startedAt} IS NOT NULL
            AND ${t.completedAt} IS NOT NULL
            AND ${t.lastError} IS NULL)`,
    ),
    check(
      'org_deletion_job_requested_actor_type_chk',
      sql`${t.requestedActorType} IN ('user', 'system')`,
    ),
    check(
      'org_deletion_job_requested_actor_consistency_chk',
      sql`(${t.requestedActorType} = 'user' AND ${t.requestedActorId} IS NOT NULL)
          OR (${t.requestedActorType} = 'system' AND ${t.requestedActorId} IS NULL)`,
    ),
    index('org_deletion_job_queued_idx')
      .on(t.requestedAt)
      .where(sql`status = 'queued'`),
    index('org_deletion_job_failed_idx')
      .on(t.requestedAt.desc())
      .where(sql`status = 'failed'`),
    index('org_deletion_job_org_id_idx')
      .on(t.orgId)
      .where(sql`org_id IS NOT NULL`),
    index('org_deletion_job_completed_at_idx')
      .on(t.completedAt.desc())
      .where(sql`completed_at IS NOT NULL`),
  ],
);

// ─────────────────────────────────────────────────────────────────────────
// Better Auth tables — session / account / verification.
//
// These are auth implementation detail and are not in the 12 production
// tables of design_p3_schema.md. user.id is uuid (uuidv7) per the production
// schema, so the FK columns here are uuid as well. session/account/
// verification keep Better Auth's default column shapes; the auth adapter maps
// Better Auth's default user fields into the production user table.
// ─────────────────────────────────────────────────────────────────────────
export const session = pgTable('session', {
  id: text('id').primaryKey(),
  userId: uuid('user_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
  token: text('token').notNull().unique(),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  ipAddress: text('ip_address'),
  userAgent: text('user_agent'),
  createdAt: timestamp('created_at', { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true })
    .notNull()
    .defaultNow(),
});

export const account = pgTable('account', {
  id: text('id').primaryKey(),
  userId: uuid('user_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
  accountId: text('account_id').notNull(),
  providerId: text('provider_id').notNull(),
  accessToken: text('access_token'),
  refreshToken: text('refresh_token'),
  idToken: text('id_token'),
  accessTokenExpiresAt: timestamp('access_token_expires_at', {
    withTimezone: true,
  }),
  refreshTokenExpiresAt: timestamp('refresh_token_expires_at', {
    withTimezone: true,
  }),
  scope: text('scope'),
  password: text('password'),
  createdAt: timestamp('created_at', { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true })
    .notNull()
    .defaultNow(),
});

export const verification = pgTable('verification', {
  id: text('id').primaryKey(),
  identifier: text('identifier').notNull(),
  value: text('value').notNull(),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true })
    .notNull()
    .defaultNow(),
});
